### ISSUE TITLE
Only count Statements caused by specific statement

### ISSUE THREAD

**Issue by zelaskoa** [Lemick/hibernate-spring-test-sql-count#3]
First thank you this library. It really works well :)

It would be nice to have also the possibility to assert sql selects/inserts/.. for a specific statement like

assertSelectsBy(() -> myRepository.findAll(),10)

**Comment by lasselindqvist** [comment]
I would love to use this as well, since I often tests in the style where there is some test specific setup done inside the test, and I don't really want to assert those, but a single controller call or service call.

It should be possible to have such methods like assertSelectsBy that record the count in the beginning of the call and compare those to the count at the end and assert it.

**Comment by lasselindqvist** [comment]
It could be just as simple as the following methods.

```
public class Assertions {
	
	public static void assertSelects(Runnable runnable, int expectedCount) {
		int size1 = HibernateStatementInspector.getStatistics().getSelectStatements().size();
		runnable.run();
		int size2 = HibernateStatementInspector.getStatistics().getSelectStatements().size();
		int realCount = size2 - size1;
		if (expectedCount != realCount) {
			String errorMessages = "Expected " + expectedCount + " select, but got " + realCount;
        	throw new HibernateAssertCountException(errorMessages);
		}
	}
}
```

**Comment by Lemick** [comment]
Thanks for the use case, I will look at it

**Comment by Lemick** [comment]
Added in 2.1.0, hope that suits your needs 😄
